# 이 파일을 복사해서 .streamlit/secrets.toml 로 저장하고 실제 값을 채워넣으세요.
# .streamlit/secrets.toml 은 .gitignore에 포함되어 깃허브에 올라가지 않습니다.

NAVER_CLIENT_ID = "Tii2e0V8YDuxnnqKXCpu"
NAVER_CLIENT_SECRET = "4YpN5BkGcw"
OPENAI_API_KEY = "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"
